[package]
name = "switchsgator"
version = "0.1.0"
edition = "2021"
description = "C# dosyalarındaki switch case yapılarındaki case bloklarını yakalamaya çalışıyorum"
authors = ["Burak Selim Şenyurt"]

[dependencies]
clap = "4.3.17"
